### ISSUE TITLE
user searchbar 

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#110]
Shaural submitted a feature request: **user searchbar**
```
A simple searchbar into the scrolling menu, which you can use to access other people's profiles.
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=54

**Comment by thehowl** [comment]
Duplicate. It's in the early issues.

On 30 March 2016 13:41:12 CEST, Schiavo <notifications@github.com> wrote:
>Shaural submitted a feature request: **user searchbar **
>```
>A simple searchbar into the scrolling menu, which you can use to access
>other people's profiles.
>```
>Despite being a smart bot, I can not automagically respond to the user
>if you have any feedback to give them. Thus, if you wish to tell 'em
>something, respond here: https://ripple.moe/index.php?p=114&id=54
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osuripple/ripple/issues/110

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thehowl** [comment]
(#7)
