### ISSUE TITLE
add channel #indonesian

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#129]
rizal12378 submitted a feature request: **add channel #indonesian**
```
maybe theres a lot of players from indonesian..can i req that channel? thanks...nice server btw :)
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=65

**Comment by thehowl** [comment]
Sì ma @xNyo chiudili gli issue
