### ISSUE TITLE
osu!tourney

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#140]
RealizeNezumi submitted a feature request: **osu!tourney**
```
its gonna be great to see a ripple community turnament
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=72

**Comment by marcostudios** [comment]
I'm not sure if reffering to #95 or he just wants to have a ripple tournament

**Comment by thehowl** [comment]
quite sure referring to #95.
