### ISSUE TITLE
Country Leaderboards

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#142]
dagreshu submitted a feature request: **Country Leaderboards**
```
Like these flags on the profile, when you click on them you can see an list with all top players from that country (inspired by osu.ppy.sh)
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=73

**Comment by marcostudios** [comment]
dupe #134
