### ISSUE TITLE
PP Su Mania.

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#163]
MS21 submitted a feature request: **PP Su Mania.**
```
A QUANDO I PP SU TUTTE LE ALTRE MODALITA'?!?! EH?!?
also i marò, e jenna è un trans.
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=78

**Comment by thehowl** [comment]
mattia sei un cazzo di fag
