### ISSUE TITLE
Why i can't connect latest/beta version?

### ISSUE THREAD

**Issue by 3pixeI** [osuripple/ripple#165]
i used ripple master branch and "https://github.com/osuripple/ripple/wiki/How-to-setup-ripple" were looking for setting up the server. Issue a certificate of ppy.sh domain , it was also completed test..

but i can't connect latest/beta version..
In pep.py the login was successful, was the failure on the client.
I want a solution to this problem.

// thanks by http://translate.google.com :D

**Comment by thehowl** [comment]
You will need to make an HTTPS certificate and install it on your PC, and make the webserver on the ripple server you're hosting use the certificate.

**Comment by AndreykaMrPvP** [comment]
Can you tell in more detail about creation of the certificate?

**Comment by insomnyawolf** [comment]
Google about them as ssl certificates.
https://www.akadia.com/services/ssh_test_certificate.html
https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl
I must say i gave up on this.

**Comment by AndreykaMrPvP** [comment]
Can you help me with the creation of the server?

**Comment by insomnyawolf** [comment]
Actually made it run but never managed to get it working with current versions.
Anything you need tell it to me trought private message at 
insomnyawolf(╯°□°）╯︵ ┻━┻#9895 (discord) 
or @insomnyawolf (twitter)

**Comment by LordDamionDevil** [comment]
Even if this is old and not supported at all i think there should of been help on how to setup the self signed certificate aswell.
