### ISSUE TITLE
pep.py mysql error :(

### ISSUE THREAD

**Issue by yunho0508** [osuripple/ripple#166]
I'm run the pep.py and write config.ini.

but pep.py say's

    raise errorclass(errno, errorvalue)
pymysql.err.ProgrammingError: (1146, "Table 'osu.bancho_settings' doesn't exist")

Please help me

**Comment by thehowl** [comment]
* You may not have created the database running migrations.php
* You may have misconfigured pep.py

I'll close this issue because, as stated in the README, **NO SUPPORT IS PROVIDED FOR ANYTHING THAT HAS TO DEAL WITH THIS CODE. USE AT YOUR OWN AND SOLE RISK.**
