### ISSUE TITLE
DB Connect Error

### ISSUE THREAD

**Issue by CocoaWiki** [osuripple/ripple#169]
Server Log
https://gist.github.com/CocoaWiki/f9fbafeea60f48e265cf4772a24ee300

config.ini
https://gist.github.com/CocoaWiki/a0ed26091d7374cf5cc38252e2be3619

**Comment by thehowl** [comment]
Literally written in the traceback. Also, as the README states:

> **NO SUPPORT IS PROVIDED FOR ANYTHING THAT HAS TO DEAL WITH THIS CODE. USE AT YOUR OWN AND SOLE RISK.**
