### ISSUE TITLE
[idk if this is dead] PHP 7.0

### ISSUE THREAD

**Issue by KadePcGames** [osuripple/ripple#170]
So i think their might be a problem when i try to migrate it just gives me this
`
PHP Warning:  require_once(/var/www/html/osu.ppy.sh/inc/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/osu.ppy.sh/inc/functions.php on line 17
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/osu.ppy.sh/inc/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/osu.ppy.sh/inc/functions.php on line 17
`

**Comment by KrykiZZ** [comment]
just use a composer

**Comment by KadePcGames** [comment]
oh lol im dumb

**Comment by KadePcGames** [comment]
shit how does one do that i haven't use linux in like 12 years jesus lol

**Comment by KrykiZZ** [comment]
https://getcomposer.org/

**Comment by KadePcGames** [comment]
[InvalidArgumentException]
  Script "migrate.php" is not defined in this package

**Comment by KrykiZZ** [comment]
I looked at your repositories ... You know, I do not want to help you.

**Comment by KadePcGames** [comment]
Alright, dude i don't use composer. Iv been looking through shit all week. I'm gettin pretty tired of this. I never used composer before. And my repos suck ass

**Comment by thehowl** [comment]
Useful information for anyone else reading the thread: install composer and use it to get old-frontend's dependencies. If you can't follow composer's step-by-step guide on how to install it, best of luck.

**Comment by KadePcGames** [comment]
oh ok
