### ISSUE TITLE
use backblaze for storage of screenshots and replays

### ISSUE THREAD

**Issue by thehowl** [osuripple/ripple#21]

**Comment by avail** [comment]
I could lend my dedicated server for such

**Comment by thehowl** [comment]
I doubt it will scale to the growing amount of data we will have lol

**Comment by thehowl** [comment]
backups are being done at the moment, which include replays and screenshots. For common use, as in accessing the files frequently, backblaze is not good enough, because it's god damn bloody fucking slow.
