### ISSUE TITLE
Bancho error

### ISSUE THREAD

**Issue by LossFirst** [osuripple/ripple#52]
File "pep.py", line 599, in <module>
    banchobot.connect()
  File "C:\xampp\htdocs\c.ppy.sh\banchobot.py", line 19, in connect
    token = glob.tokens.addToken(999)
  File "C:\xampp\htdocs\c.ppy.sh\tokenList.py", line 21, in addToken
    newToken = osuToken.token(__userID)
  File "C:\xampp\htdocs\c.ppy.sh\osuToken.py", line 65, in __init__
    self.username = userHelper.getUserUsername(self.userID)
  File "C:\xampp\htdocs\c.ppy.sh\userHelper.py", line 172, in getUserUsername
    return glob.db.fetch("SELECT username FROM users WHERE osu_id = ?", [userID]
)["username"]
TypeError: 'NoneType' object is not subscriptable

What is this?

**Comment by thehowl** [comment]
Have you set up your db using the migrate.php tool?

On 9 March 2016 12:45:40 CET, LossFirst <notifications@github.com> wrote:
>  File "pep.py", line 599, in <module>
>    banchobot.connect()
>  File "C:\xampp\htdocs\c.ppy.sh\banchobot.py", line 19, in connect
>    token = glob.tokens.addToken(999)
>  File "C:\xampp\htdocs\c.ppy.sh\tokenList.py", line 21, in addToken
>    newToken = osuToken.token(__userID)
>  File "C:\xampp\htdocs\c.ppy.sh\osuToken.py", line 65, in __init__
>    self.username = userHelper.getUserUsername(self.userID)
>File "C:\xampp\htdocs\c.ppy.sh\userHelper.py", line 172, in
>getUserUsername
>return glob.db.fetch("SELECT username FROM users WHERE osu_id = ?",
>[userID]
>)["username"]
>TypeError: 'NoneType' object is not subscriptable
>
>What is this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osuripple/ripple/issues/52

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thehowl** [comment]
Closing to clear up non-active issues. Feel free to reopen, should you have problems with it.
