### ISSUE TITLE
Friending yourself

### ISSUE THREAD

**Issue by xNyo** [osuripple/ripple#66]
Reported by Vert

This is also a bug on normal osu!, but it's only while you have your client open. It resets after you restart. On Ripple, though, this seems permanent with no way of removing it lol http://ripple.moe/ss/clag8JaR.jpg You type this in a non-PM chat (#osu or any other) and then it says "You are now friends with [your own username]". On the Ripple site, it shows up that you have a mutual with yourself as well, which is kinda funny. http://puu.sh/nERxl/64c421d2a8.png

**Comment by marcostudios** [comment]
Now i don't have any friends

thank mr nyo

**Comment by thehowl** [comment]
#ILBUGGDEGLIAMICI
