### ISSUE TITLE
very important fitcha

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#85]
Howl submitted a feature request: **very important fitcha**
```
dis be a very impurtunt fitcha it shoudl meme it and xddd
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=47

**Comment by thehowl** [comment]
fuck you stampa piede

**Comment by xNyo** [comment]
SUHAUIUIAHSIUHAHAHAHAH
