### ISSUE TITLE
hOI!!! NYEH HEH HEH HEH HEH!

### ISSUE THREAD

**Issue by stampapiede** [osuripple/ripple#86]
Howl submitted a bug report: **hOI!!! NYEH HEH HEH HEH HEH!**
```
hi papyrus tvb
```
Despite being a smart bot, I can not automagically respond to the user if you have any feedback to give them. Thus, if you wish to tell 'em something, respond here: https://ripple.moe/index.php?p=114&id=48

**Comment by xNyo** [comment]
Quality meme (y)
